# Generated by Django 4.2.5 on 2023-12-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAPP', '0002_blogs_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
